### ISSUE TITLE
Create CITATION file

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#100]
**[Original report](https://bitbucket.org/glotzer/signac/issue/100) by Carl Simon Adorf (Bitbucket: [csadorf](https://bitbucket.org/csadorf), GitHub: [csadorf](https://github.com/csadorf)).**

----------------------------------------

We should follow the guidelines of 

https://www.software.ac.uk/blog/2016-10-06-encouraging-citation-software-introducing-citation-files

and 

https://www.software.ac.uk/blog/2018-10-02-hacking-software-citation-implementation-citation-file-format-hack-day-rse18

to make citation easier for users.

**Comment by bdice** [comment]
Related: https://github.com/adrn/CitationPEP

**Comment by csadorf** [comment]
We have a CITATION.cff file.
