### ISSUE TITLE
Implement a `signac.get_job()` function

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#108]
**[Original report](https://bitbucket.org/glotzer/signac/issue/108) by Carl Simon Adorf (Bitbucket: [csadorf](https://bitbucket.org/csadorf), GitHub: [csadorf](https://github.com/csadorf)).**

----------------------------------------

The idea is to be able to "get" a job from the local directory. Use cases for example when opening a `signac shell` from within a signac workspace directory.

The main challenge is that the current data model does not associate a job workspace directory with one specific project.

See also related pull request: https://bitbucket.org/glotzer/signac/pull-requests/62

**Comment by csadorf** [comment]
@bdice I don't think that there is a perfect solution for this within the current conceptual framework, but we might get close to one. What do you think? Should we complete the implementation that you started prior to 1.0 even if there are some ambiguities?

**Comment by bdice** [comment]
@csadorf Yeah, it would be nice to start from something close to what I wrote (see #118). I think it was working for several (all?) of the cases that I had in mind, though certainly not _all_ the cases that might be possible under the current model.

**Comment by csadorf** [comment]
Resolved with the merge of PR #118.
