### ISSUE TITLE
Chain calls to job methods, specifically `.init()`

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#120]
### Feature description

I would like to be able to call `job = project.open_job(statepoint).init()`, which would be possible if `init()` returned `self`. This is related to #71. Other methods that could be chained if desired: `reset_statepoint`, `update_statepoint`, `clear`, `reset`, `move`, `sync`.

### Proposed solution

Make `init()` return `self`.

**Comment by csadorf** [comment]
This is amazing. I was just about to create this issue **today**. And yes, that is a perfectly reasonable solution!

**Comment by csadorf** [comment]
Resolved with merge of #125 .
