### ISSUE TITLE
Use config's signac_version to track schema version for easier migration.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#165]
### Feature description

Currently it appears that we have an implied Project config value, `'signac_version': (0, 1, 0)`.
https://github.com/glotzerlab/signac/blob/ba14a1b60c7ba431d8c8e54d6909203248cccca9/signac/common/validate.py#L55

### Proposed solution

We should update the configuration to store the actual version of signac used to create or initialize the project. This will make migrations easier and make something of this currently unused config value. We explicitly have backward compatibility to 0.1.0 already so this won't break anything.

**Comment by bdice** [comment]
@csadorf Does this still make sense to include? I think that versioning our _schema_ is a better solution in the long term than versioning signac.rc by the package version.

**Comment by csadorf** [comment]
Yes, it should be the schema.

**Comment by bdice** [comment]
@csadorf So is the name supposed to be `signac_version` or `signac_schema_version`?

During project initialization, do we just add a field `config['signac_schema_version'] = [0, 1, 0]`?

**Comment by csadorf** [comment]
Yes, I think we should add that and also check compatibility assuming semantic versioning. So, there should be a warning if we are operating on a newer version and it should fail if the major version is newer.
