### ISSUE TITLE
Can't assign dictionaries containing integer keys into job.document

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#168]
### Description

I wanted to store a key-value mapping of the form `{1: 'a', 2: 'b'}` into a sub-key of a job document. I incorrectly expected that this would be encodable as JSON. I researched it and found out that JSON only allows string keys. However, the error triggers when checking for dots, and this doesn't seem like the right place. A second problem with silent failure is also confusing.

### To reproduce

First problem: error triggers for unexpected reason.
```python
>>> job.doc['mapping'] = {1: 'a', 2: 'b'}
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".../lib/python3.6/site-packages/signac/core/synceddict.py", line 185, in __setitem__
    self._data[self._validate_key(key)] = self._dfs_convert(value)
  File ".../lib/python3.6/site-packages/signac/core/synceddict.py", line 106, in _dfs_convert
    ret[k] = root[k]
  File ".../lib/python3.6/site-packages/signac/core/synceddict.py", line 185, in __setitem__
    self._data[self._validate_key(key)] = self._dfs_convert(value)
  File ".../lib/python3.6/site-packages/signac/core/synceddict.py", line 90, in _validate_key
    if '.' in key:
TypeError: argument of type 'int' is not iterable
```
Second problem: silent failure should be loud.
```python
>>> job.doc = {1: 'a', 2: 'b'}
>>> job.doc
{}
```

### System configuration

Please complete the following information:

 - Operating System: Ubuntu 18.04 (Bash on Windows)
 - Version of Python: 3.6.8
 - Version of signac: 1.0.0

**Comment by bdice** [comment]
For comparison, [tinydb](https://github.com/msiemens/tinydb/) converts non-string keys into strings by [just using `json.dumps`](https://github.com/msiemens/tinydb/blob/50eee49e392e3be32597c945a62f6210e166d9b2/tinydb/storages.py#L112). This behavior may be preferable to getting errors / data loss, perhaps accompanied by a warning.
```python
>>> json.dumps({1: "a", 2: "b"})
'{"1": "a", "2": "b"}'
```

**Comment by csadorf** [comment]
The behavior that you are seen is unintended and especially your second minimal example is surprising to me. But I don't think that explicit conversion is a good idea.

**Comment by vyasr** [comment]
A first pass at this would just involve at least making the errors more descriptive. But beyond that, what do we think is the correct behavior? Just write integer keys as strings, with some warning that such keys are converted? That would also cause problems when accessing the keys of a SyncedDict, though; what would be the expected result of `job.doc[1]` vs `job.doc["1"]`?

**Comment by bdice** [comment]
@vyasr I think you're right, just warn the user that non-string keys are converted. `job.doc[1]` and `job.doc["1"]` should return the same thing - we would convert keys and warn when setting *and* getting.

**Comment by bdice** [comment]
But @csadorf doesn't think implicit conversion is good - I can accept that and I'm fine with rejecting "implicit" conversions and continuing to throw errors in cases like the first one, just with a better message. The biggest problem is case 2 above, where no error was thrown.

**Comment by vyasr** [comment]
Right, so I would advocate for the second example to just throw an error, for starters. Making that change is critical. Then we can discuss the appropriate casting behavior; I might be OK with implicit conversion, but it would have to be very noisy. I have the same concerns Simon likely has about that, so I'm also OK with not supporting implicit conversion if we think making it a very noisy conversion is ugly and still may lead to unexpected results for users.

**Comment by csadorf** [comment]
@bdice I'm unable to reproduce your second example:
```python
>>> job.doc = {1: 'a', 2: 'b'}
>>> job.doc
{}
```

With respect to the overall problem: I ran a few tests and found that we are currently doing an implicit conversion when assigning a dict with non-string keys to either `sp` or `doc`. In order to maintain backwards-compatibility, I'll enable the exact same behavior when assigning non-string keys. We can opt to show a user-warning if we feel strongly about this. It seems to me that while implicit conversion might lead to bugs in some cases, it's closer to the average user's expectations than throwing an error. It's certainly less convenient.

**Comment by vyasr** [comment]
I can confirm what you found:
```
>>> job.doc = {1: 'a', 2: 'b'}
>>> job.doc
{"1": "a", "2": "b"}
```

So we should probably also do an implicit conversion for nested keys. I don't feel strongly that a warning is needed, but perhaps it should be mentioned in the documentation [here](https://docs.signac.io/en/latest/jobs.html#the-job-document).
