### ISSUE TITLE
Improve "dots in keys" error message.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#170]
### Feature description

If there's a dot in a key, the error message that shows up makes it really hard to find _where_ the problematic key is located. @rosecers reported challenges with her project because the invalid key was difficult to trace. (Ultimately @csadorf located the invalid key in the project document, not the job statepoints/documents where one might have expected to find it.)

### Proposed solution

We could edit the `_validate_key` method (https://github.com/glotzerlab/signac/blob/88ede71b9d16a61c92f43f05c9662ef6725518b2/signac/core/synceddict.py#L92), so that the error also prints the key.

Something like: `The use of '.' (dots) in keys is invalid: {key}`

Ideally we could show a path to the problematic JSON file, but the `SyncedDict` implementing the validation method is a parent class of the `JSONDict` so it may require a little more thought / planning to show that.

**Comment by csadorf** [comment]
Fixed with merge of #205.
