### ISSUE TITLE
Bug in JSON error checking

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac#172]
### Description

The rapidjson package does not have a `decoder` submodule. Since we don't have a corresponding compatibility layer, things like `json.decoder.JSONDecodeError` fail.

### To reproduce

```
$ signac init json_decoder
$ signac find '{"x": True}'
27958648a9e57fcd66ae5e31ff3359e9
$ signac find '{"x": True}'  # This is invalid JSON, the expected behavior is to raise an error indicating that the JSON is invalid
Error: module 'signac.core.json' has no attribute 'decoder'  # The actual output
```

**Comment by bdice** [comment]
Seems this was addressed in rapidjson here:
https://github.com/python-rapidjson/python-rapidjson/commit/8c1f7647c2430857f31724d1d219533f662f9ca9
https://github.com/python-rapidjson/python-rapidjson/issues/118

...and released about two weeks ago: https://github.com/python-rapidjson/python-rapidjson/blob/master/CHANGES.rst

Good things come to those who wait! That makes solving this issue a bit cleaner.
