### ISSUE TITLE
Docs version not bumped

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#178]
It looks like the Sphinx docs didn't get their version bumped from 0.9 to 1.0.

https://github.com/glotzerlab/signac/blob/master/doc/conf.py#L82

It may be possible to use bumpversion's [file-specific configuration](https://github.com/peritus/bumpversion#file-specific-configuration) for `conf.py` to prevent this from happening in the future.

Or we could just treat `version` and `release` as the same in `conf.py`, instead of differentiating short version and long version.

**Comment by csadorf** [comment]
Fixed with release of version 1.1.0.
