### ISSUE TITLE
`signac view` fails when statepoints contain forwardslashes

### ISSUE THREAD

**Issue by klywang** [glotzerlab/signac#213]
### Description

`signac view` cannot create folders when statepoints contain forward slashes (ie, if a statepoint value is '/oasis/scratch/some_file.txt')

### To reproduce

`signac view`

Example of statepoint: 
 `{'pot_file': '/oasis/scratch/path/to/file/some_file.out'}`

### Error output

Error: [Errno 13] Permission denied: '/oasis'### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: macOS Moajve (10.14.4)
 - Version of Python [e.g. 3.7]: 3.7.3
 - Version of signac [e.g. 1.0]: 1.2.0

**Comment by vyasr** [comment]
I think the proper behavior here is to just throw a more descriptive error message. Right now it just gives a permission denied error in this case, we should at least change it to raise an Exception that informs the user why it doesn't work. I don't think that this is necessarily something that we should support, because it would require modifying the values to avoid containing file separators.

**Comment by csadorf** [comment]
I agree that adding a more descriptive error message and potentially suggesting a work-around is the way to go. We have been pretty liberal about what a state point key and value may contain as long as it is JSON-encodable and issues like that are kind of bound to happen.

My suggested solution is to explicitly check for `os.sep` in keys and values and simply error out. A potential work-around is to only include keys and values that do not contain these values.

@klywang Would that be a satisfactory solution?

**Comment by klywang** [comment]
@csadorf Yeah that sounds good!

**Comment by mikemhenry** [comment]
Just to clarify the behavior we want:
paths are okay in state points but will prevent view from working (with a helpful error message)

**Comment by vyasr** [comment]
Yes, I think that's the best option. We could potentially disallow them in 2.0, but I don't think it's necessary since it only causes problems for views.

**Comment by vyasr** [comment]
Resolved by #233.
