### ISSUE TITLE
Refactor internal use of deprecated `Project.get_statepoint`

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#227]
The `Project.get_statepoint` function is deprecated but used internally. This should be refactored.

_Originally posted by @csadorf in https://github.com/glotzerlab/signac/pull/220_

**Comment by bdice** [comment]
Currently `Project.get_statepoint` is used in `Project.open_job` when initializing the `Job` object.

This might be easiest to do as a part of (or after) #239, so I advocate waiting on that PR.

**Comment by vyasr** [comment]
Could you clarify why this should wait on #239? Just from reading the issue, it seems unrelated. The `get_statepoint` actually does things that are redundant when called from `open_job` (like looking in the cache again), so I would expect that `open_job` would just directly call `_get_statepoint_from_workspace` in the case that currently falls back to `get_statepoint`.

**Comment by bdice** [comment]
@vyasr Initializing the Job object will look different if it's lazy. The state point may not be required at all, and some code paths (potentially including uses of this deprecated function) will be removed.

**Comment by bdice** [comment]
@vyasr Ooh, maybe you're right. I'll retract my previous comment. Maybe this can be resolved without any dependence on #239, though the changes will probably conflict.

**Comment by vyasr** [comment]
@vishav1771 can you comment on this issue so that I can assign it to you? Thanks!

**Comment by vishav1771** [comment]
@vyasr Sure, assign me:)
