### ISSUE TITLE
Different arithmetic operator syntax for 'not equal to' in documentation

### ISSUE THREAD

**Issue by zhou-pj** [glotzerlab/signac#240]
### Description

The documentation shows a different arithmetic operator syntax for not equal to($neq) in collection that seems to be a typo. 
code location: signac/contrib/collection.py
documentation links:
https://docs.signac.io/projects/core/en/latest/api.html#signac.Collection.find
https://docs.signac.io/en/latest/query.html#operator-expressions

**Comment by csadorf** [comment]
Yes, that's a typo. Any committer may fix this without PR.

**Comment by csadorf** [comment]
Fixed on master.

**Comment by csadorf** [comment]
@zhou-pj Thank's for noticing and reporting!
