### ISSUE TITLE
signac diff

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac#248]
### Feature description

Add the functionality to call `signac diff` to compare two or more state points. This could also be extended to comparing files, job docs, etc. 

### Proposed solution

partially solved at #247 

### Additional context

Any input from @bdice @csadorf @vyasr @b-butler @mikemhenry is very welcome!

**Comment by csadorf** [comment]
@atravitz Could you outline the proposed API both on the Python and the CLI level?

**Comment by atravitz** [comment]
CLI usage: 
`signac diff {job_ids}` where `{job_ids}` is any number of signac job_ids

returns: pretty-printed job ids, each with dictionary of the job's unique state points (the state point minus the intersection of all the state points of the jobs passed in)

python:
`diff_jobs(*jobs)`where `{jobs}` is any number of signac jobs

returns: a dictionary where keys are state point ids and values are a dictionary of the job's unique state points (the state point minus the intersection of all the state points of the jobs passed in)


happy to take suggestions!

**Comment by bdice** [comment]
@atravitz I think this is a good API proposal. I may be slightly biased because we discussed some of this already, so it would be great to get feedback from others.

**Comment by bdice** [comment]
@atravitz Could you expand on the API concept a little bit? I have a few things in mind:

1. What flags / arguments are supported for the command line `signac diff`? Is this list exhaustive or are there other flags we should consider adding? Some flags might complicate the design, e.g. diffing all jobs that match a filter, which I can't remember if this PR supports already.
2. We don't need to implement this now, but let's draft a concept of what the API might look like if we wanted to diff job documents or projects. This helps ensure that we aren't making API choices that we would want to change later.

**Comment by atravitz** [comment]
CLI usage:
signac diff {job_ids} where {job_ids} is any number of signac job_ids
If no job_ids passed, the diff will operate on the entire project.
--filter, -f : only diff jobs matching this state point filter
--sort, -s: sort the state point keys for output (I still need to add this)
--pretty : print results in pretty format, an optional argument to this flax specifies the max depth a state point is printed (should I default to this and not specify it as an option?)

returns: pretty-printed job ids, each with dictionary of the job's unique state points (the state point minus the intersection of all the state points of the jobs passed in)

python:
diff_jobs(*jobs)where {jobs} is any number of signac jobs


I agree that we should have some foresight on the api for diffing projects or documents, but that those are a much lower priority.

**Comment by vyasr** [comment]
Do we have a sense for how slow the diff is to compute? If it's very slow for large projects, we might want to make users explicitly specify `--all` or something to avoid accidentally calling a diff on a 1e5 job project that never finishes.

I think that it makes a lot of sense to put most of the logic into a `diff_mapping` (or whatever name) function that performs this diff on any object that satisfies `isinstance(collections.abc.MutableMapping)`. That would allow us to have `def diff_jobs(*jobs, *args, **kwargs): return diff_mapping([job.sp for job in jobs], *args, **kwargs)` while also reusing that for documents in the future.

I'm less concerned about projects; since we wouldn't be diffing them on a primary key (e.g. root_directory, name), as long as we name functions so that `diff_project` remains sufficiently unambiguous we don't need to consider the behavior of that function when designing this API.

**Comment by csadorf** [comment]
@atravitz What is usually helpful in working out an API is to compile a few relevant user stories and then provide examples how these would be realized. Here are two examples of previous proposals where we did exactly that:

1. [The import/export API](https://github.com/glotzerlab/signac/issues/91)
2. [The cross-reference API](https://github.com/glotzerlab/signac/issues/96)

The proposal does not have to be that detailed for this particular function, but I would like to see at least one or two examples how some of these user stories would be realized. Here are some user stories that I can come up with from the top of my head, but it might not be exhaustive:

1. I would like to determine how a job's state point differs from another job's state point.
2. I would like to determine how a job's document differs from another job's document.
3. I would like to determine how a job's data store differs from another job's data store.
4. I would like to determine which files are in one job, but not the other.
5. All of the cases above, but with more than two jobs.
6. All of the cases above, but limited to specific keys.

We are in no way obligated to implement all of these use cases right away (or at all), but we should have put some foresight into how we would do it, should we decide to do so. A well-structured and coherent API can make or break a user experience so this is crucially important.

> Do we have a sense for how slow the diff is to compute? If it's very slow for large projects, we might want to make users explicitly specify --all or something to avoid accidentally calling a diff on a 1e5 job project that never finishes.

@vyasr I don't think we have an `--all` option in any of the other CLI sub commands which is a strong indicator that we should not this here either. IMO, a better way to handle this would be to provide some user feedback, for example in the form of a progress bar, and then enable users to cancel the process with *Ctrl+Z* for instance.

**Comment by atravitz** [comment]
Here's a short proposal following a similar structure (thanks for the examples, I wasn't quite sure how to articulate):

# About 
This feature will allow users to quickly compare multiple jobs (and potentially projects) to determine the key/value pairs that differ between the jobs. This can be used for quick checks on the command line, or as part of a workflow on the python level.

### Use Cases this PR should cover
1. User wants to determine how a job's state point differs from another job's state point.
2. User wants to compare all jobs that match a job filter.
3. User wants to compare two state points from different projects.
4. All of the above cases, but with more than two jobs.
5. All of the above cases, but limited to specific keys.

### Use Cases this PR will *not* cover, but might in the future
1. User wants to determine how a job's document differs from another job's document. 
2. User wants to determine how a job's data store differs from another job's data store.
3. I would like to determine which files are in one job, but not the other. 

# API

## Command Line

`signac diff {job_ids}` where `{job_ids}` is any number of signac job_ids
If no job_ids are given, the diff will operate on the entire project. If a single job_id is given, the operation will return an empty dict (it could also return the full state point, either seem reasonable to me).

### command line options
`--filter, -f`: only diff jobs matching this state point filter
`--sort, -s`: sort the state point keys for output (I still need to add this)
`--pretty`: print results in pretty format, an optional argument to this flax specifies the max depth a state point is printed (should I default to this and not specify it as an option?)

`return`: pretty-printed job ids, each with dictionary of the job's unique state points (the state point minus the intersection of all the state points of the jobs passed in)

Example: 
`signac diff ffe 542`

## Python
`diff_jobs(*jobs)` where `jobs` is any number of signac jobs
`return`: a dictionary where keys are job_ids and values are state point dictionaries.


I'll add some examples as well
