### ISSUE TITLE
Permissions on .signac_shell_history give cryptic error

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#262]
### Description

When launching `signac shell`, we got a cryptic error: `Error: [Errno 13] Permission denied`. This happened because I was collaborating with @tommy-waltmann. I ran `signac shell` and the file was created with permissions `600`, meaning that he couldn't read it. We should catch errors when the `.signac_shell_history` file is not readable, throw a warning, and continue to launch the shell with no history saved.

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Linux
 - Version of Python [e.g. 3.7]: Python 3.7
 - Version of signac [e.g. 1.0]: 1.2

**Comment by bdice** [comment]
## Suggested changes to resolve this issue:

Edit this code to show a warning if the `.signac_shell_history` file is not readable/writable, and allow this exception to pass (don't raise). The warning should say something like ".signac_shell_history could not be read/written. The history of this shell will not be saved." Ideally, the warning text should be specific about the permissions it's missing (read or write). https://github.com/glotzerlab/signac/blob/6bf33e097e6545fe7e1d14fddd6e2f35cd23a4bd/signac/__main__.py#L1042-L1051

Test it by creating a `.signac_shell_history` file that is not user-readable/writeable. Make sure to test all combinations of file permissions (read/write, read-only, write-only, no read or write).

**Comment by ac-optimus** [comment]
@bdice can I work on this issue if no one is working on it currently?
Thanks!

**Comment by csadorf** [comment]
@ac-optimus Absolutely!

Btw, might be better to tag [signac-committers](https://github.com/orgs/glotzerlab/teams/signac-committers), anyone of them can assign you to an issue.

**Comment by ac-optimus** [comment]
@csadorf sure,  Thanks !

**Comment by vyasr** [comment]
This issue was resolved by #279.
