### ISSUE TITLE
Add mapping from a dictionary with dotted keys to a nested dictionary

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac#268]
### Feature description

We should write an internal function to convert dictionaries with dotted keys e.g. `{'a.b': 'c'}` to `{'a': {'b': 'c'}}`. We currently have the reverse functionality implemented for Collections. This feature is also partially implemented in a few parts of the code, so we should generalize them and centralize the code.

### Proposed solution

Ideally this would be a simple recursive function that does something like a string split of keys and then recursively constructs dictionaries until the string is empty.

**Comment by vishav1771** [comment]
@vyasr I would like to work on this issue. A have written function to convert dictionary with dotted keys to nested dictionary. But I have doubt about where the new function to be added and called(attrdict or jobs).

**Comment by vyasr** [comment]
Hi @vishav1771, that's great! This logic should actually live at the level of signac Collections, which are the core data structure that signac uses for things like searching and filtering. The code for collections is contained in `signac/contrib/collection.py`. As noted in the issue, the reverse functionality from what is requested is already implemented: you can see that functionality in the `_traverse_tree` method in that file. It goes through a dictionary and recursively appends keys to keys in nested dictionaries to create e.g. `{'a.b': 'c'}` from `{'a': {'b': 'c'}}`.

This issue originally popped up in the implementation of #247. The file `signac/diff.py` contains an implementation of this feature that was sufficient for the use-case in that pull request. @bdice @atravitz do you recall where else you found partial implementations of this type of mapping? Collecting the other examples would be helpful for @vishav1771 in determining how general his function needs to be.

**Comment by bdice** [comment]
@vyasr @vishav1771 I remember that I looked through the code for import/export and views, but I don't think I found any implementations of the direction I needed (which is why we wrote the implementation in `signac/diff.py`).

I'm also not sure if this functionality is specific to Collections. For example, the diff feature doesn't use Collections. I think the import/export code might have its own implementation as well (can't recall), so it may make sense to include as a utility function somewhere more global.

**Comment by vishav1771** [comment]
@bdice @vyasr I have written the function for nested dictionary which should do the task. I am attaching code snippet below:
```def _nested_dict(statepoint):
    points=statepoint.items()
    for key,val in points:
        key_ = key.split('.')
        if len(key_ ) > 1 :
            for ele in key_[:0:-1]:
                val={ele:val}
            statepoint[key_list[0]]=val
            del statepoint[key]
    return statepoint
```
Kindly review this.

**Comment by bdice** [comment]
@vishav1771 We already have a function that converts dictionaries with dotted keys to nested dictionaries in `signac/diff.py` -- see here: https://github.com/glotzerlab/signac/blob/dc870ac06159cae97e1475894913d1def567555e/signac/diff.py#L7-L28

This issue is really about refactoring that logic with the logic in `signac/contrib/collection.py`, where there is a method `_traverse_tree` to do the opposite task. Should those functions be in the same place? Do these functions belong in Collections or someplace else? To solve this issue, someone needs to review the code base for other places that these kinds of functions are used. This may require some familiarity with the package as a whole.

**Comment by vishav1771** [comment]
@bdice Thankyou, for clarification. I'll stop working on this issue for now and try to make myself more familiar with the library. Can you suggest some other issues which I can work on?

**Comment by vyasr** [comment]
@vishav1771 there are a few good issues that you could work on. Let me describe them in a bit more detail:

- #227 is about the removal of a deprecated method that is still used internally in a number of places in signac. Fixing that issue involves going through `signac/contrib/project.py` and replacing all uses of the deprecated method `Project.get_statepoint` with `Project.open_job(jobid).sp`. This issue might be a good first one to tackle since it's relatively self-contained.
- #230 involves an issue with our synchronization code. In signac, you can think of the contents of a job state point as describing its primary key, the set of parameters that uniquely identify the job within the project. The package has features to extract the schema of a project, where the schema describes the range of parameters present in all state points. This feature is used by signac's synchronization feature, which allows the copying or in-place update of jobs from one project into another. In #230, a user pointed out that in some cases two identical schema are mistakenly being identified as being different, which affects our ability to synchronize. Fixing this issue would involve first identifying why our schema comparison code thinks the two schema he has are different, and then proposing a fix for this problem. This issue might be more fun to tackle if you like this kind of work, and it would have an immediate impact on certain workflows.
- #212 is a discussion of switching our testing framework to use `pytest` instead of Python's built-in `unittest` library. In case you're not familiar, `pytest` is a third-party testing that is largely compatible with unit tests written for `unittest`, but provides plenty of additional features that make it much easier to write, maintain, and run tests. All of our existing tests already work with `pytest`, so the first step in making this change is simply to update things like our testing framework and our docs to use `pytest`. However, we would also like to use something like `unittest2pytest` to rewrite our tests in more `pytest` style, which is probably a larger undertaking since it's likely that not all of our tests will trivially convert automatically. This issue would be a great opportunity for you to familiarize yourself with the code base more broadly and get to know its features.

We'd love to have your help on whichever of these issues you find most interesting! I'd appreciate if you posted further questions about these issues in our Slack channel, and we can continue our discussion there.

**Comment by vishav1771** [comment]
@vyasr @bdice I think I am now able to start working on this issue. Kindly brief me about what I need to do?

**Comment by vyasr** [comment]
Sure, you are welcome to take a stab at this! Be warned that this issue will be a bit tricky because it requires looking through large parts of the code base. Also, none of the maintainers have done this thorough sweep yet, so we may have to go through a few iterations to get everything right as we collect more information. As long as that sounds OK to you, I'm happy to have you work on this issue, as it will help you get much more intimately familiar with the internals of the code base. If you get started and find yourself getting stuck, feel free to let us know and move on to another issue; we can always come back to this one later.

Before we actually resolve this issue, I think we need to resolve the follow-up issue, so I'm going to tag you on that one and we can continue discussing there.
