### ISSUE TITLE
H5Store pytest is failing on MacOS but passes on Linux

### ISSUE THREAD

**Issue by klywang** [glotzerlab/signac#281]
### Description

Currently, one of the multiprocessing unit tests, `test_single_writer_multiple_reader_same_instance` from `test_h5store.py`, will fail on MacOS. The test passes on Linux and is skipped on Windows due to failure for an unknown reason. 

My system has `HDF5` version 10.4.1 and `h5py` version 2.10.0.

### To reproduce
On Mac:
```bash
$ cd /path/to/signac/
$ pytest tests/test_h5store.py -k "TestH5StoreMultiProcessing"
```
This will return an error. This test will pass on Linux (tested locally and tested in CI) and is skipped on Windows (not tested locally and tested on CI)

### Error output

```bash
OSError: Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: macOS 
 - Version of Python [e.g. 3.7]: 3.8.1
 - Version of signac [e.g. 1.0]: 1.3.0

Or copy & paste the output of: `python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__)'`

**Comment by csadorf** [comment]
I've marked this as a bug, since this might be a potential issue on Mac OS systems. @klywang Would you be willing to add the Mac test to the CI pipeline?

**Comment by klywang** [comment]
Would this branch be categorised as `fix` or `misc`?

**Comment by bdice** [comment]
> Would this branch be categorised as `fix` or `misc`?

Branch names are very flexible - maybe something like `ci/mac`. Your call!

**Comment by vyasr** [comment]
@klywang did you have any luck figuring out why this fails?

**Comment by b-butler** [comment]
@klywang is this still an issue? If so, do you have time to add the mac test to our CI pipeline, and potentially find the bug?

**Comment by vyasr** [comment]
I'm observing this issue again and will try to resolve it.
