### ISSUE TITLE
Proposal: Revise the signac configuration system to use the TOML format

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#283]
### Summary

The use of [INI-files](https://en.wikipedia.org/wiki/INI_file) in combination with the [configobj package](https://pypi.org/project/configobj/) for managing signac's configuration has been a pain point for quite some time now. With a signac 2.0 release on the horizon, I'd like to propose to use the more modern [TOML-format](https://github.com/toml-lang/toml) ([wikipedia article](https://en.wikipedia.org/wiki/TOML)) and adopt a better library for managing the configuration.

### Proposed change

We reinterpret the `signac.rc` files in the TOML-format instead of INI-format and thus increase robustness and ease of parsing and modification of these files. The TOML-format has made quite some [impact](https://everythingsysadmin.com/2015/06/toml-vs-json.html) on the developer community in the past few years and is widely regarded as superior to INI (ill-defined), yaml (complex), and [JSON (not human-friendly)](https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/) as a standardized, robust, and human-readable format for configuration files.

To implement this, we would replace the configobj package with the [anyconfig library](https://github.com/ssato/python-anyconfig) **(or a better alternative!)** for managing signac's configuration and simply reinterpret current files as TOML. 

During a transition period (prior to the release of 2.0), whenever formatting issues are encountered during parsing, signac should 
1. make a reasonable attempt at fixing these, or
2. warn if that is not possible and fall-back to parsing as INI.

After the release of 2.0, non-fixable formatting issues should lead to an error condition, forcing users to update their configuration files.

### Additional context

The use of JSON files as configuration files is largely considered to be bad practice, since JSON files are not easily modified by humans and not well diffable.

While the YAML-format is maybe easier to write and modified by humans compared to JSON, it is considered a fairly complex format and parsers that are able to handle the full standard are difficult to find, implement, and install. There are also some [security concerns](https://en.wikipedia.org/wiki/YAML#Security) about arbitrary code execution.

The TOML-format is standardized and likely superior to all alternative formats for the given purpose and is for example proposed as the standard format for the specification of minimum build system requirements as part of the provisional [PEP 518](https://www.python.org/dev/peps/pep-0518/).

This is a [good comparison of technical details](https://gohugohq.com/howto/toml-json-yaml-comparison/) between TOML, JSON, and YAML.

### Open questions

- [ ] If accepted, would we also want to transition to use `signac.toml` instead of `signac.rc` as the standard configuration file name?
- [ ] If the answer to the question above is "yes", what about `.signacrc`?
- [ ] We would likely need to add the very lightweight *toml* dependency, but do we need a more sophisticated library for the management of the configuration? If yes, which one?

**Comment by csadorf** [comment]
@glotzerlab/signac-committers I'd like to get some feedback on this and also have a preliminary decision whether we should _consider_ this, before working this out any further.

**Comment by csadorf** [comment]
We should probably also look at [dynaconf](https://dynaconf.readthedocs.io/en/latest/).

**Comment by b-butler** [comment]
TOML configuration is an interesting proposition. In general, I do think it is more readable than JSON is by default. I think this definitely is worth some consideration. If we weren't considering the project's history, I would say that TOML out of the three makes the most sense (we don't need all the power -- read complexity -- of YAML and TOML is easier and more readable than JSON -- I would imagine especially for new or novice coders/developers). These are my thoughts anyways.

**Comment by vyasr** [comment]
I think this would be a positive change and would approve at least considering the direction in which to take this.

**Comment by vyasr** [comment]
We should keep in mind #197 so that we don't try to simultaneously implement both changes.

**Comment by csadorf** [comment]
Should we put this on a 2.0 milestone?

**Comment by vyasr** [comment]
@csadorf let's leave all the issues associated with #527 open a little longer. I'm hoping to get to that issue soon. I'm in favor of using signac-flow as a testbed for making this change to TOML (or other) and deciding on the appropriate format, which corresponds to step (2) in #527 . Depending on how things go, I think it's worth documenting the results and the decision here (and similarly for the other issues associated with #527) for future discovery.

I suspect that the thread on #527 will quickly become unmanageable if we move all discussions there. On the other hand, if I don't manage to move this forward in the near future we can close some of these issues in the interest of avoiding issue bloat.

**Comment by vyasr** [comment]
Closing this as wontfix. We're interested in this change, but it's an extremely low priority and not something anyone plans to dedicate time to. If we do make this change in the future, it will only necessitate a schema version bump, not any API changes, so it would be a minimally disruptive change that is acceptable to make even if it comes a short time after the release of signac 2.0.
