### ISSUE TITLE
Remove support for rapidjson

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#285]
### Feature description

The rapidjson library is optionally supported by signac. Currently this support is enabled by default if the rapidjson library is installed. From the discussion in #171, we would like to deprecate support for rapidjson. The rapidjson support is implemented in this file:
https://github.com/glotzerlab/signac/blob/master/signac/core/json.py

### Proposed solution

There should be no API breaking changes as a result of removing rapidjson. I'm not sure if this change requires a proper deprecation cycle -- it may be sufficiently minor that we can just remove rapidjson support.

Some options:
1. Remove rapidjson support, just a clean break. **This is my preference.**
2. Throw a deprecation warning if rapidjson is automatically loaded. Since rapidjson is currently loaded by default, I dislike this approach because it would be noisy. The only easy way to hide the warning would be to ask users to uninstall rapidjson. That seems silly.
3. Make rapidjson opt-in (instead of automatic) with a configuration variable. However, that's a nontrivial amount of work and conflicts with the discussions in #171 about why we want to remove alternative JSON in the first place.

I would like a second opinion from @glotzerlab/signac-committers.

### Additional context

Minor refactoring to allow potential support for other JSON backends in the future may be worthwhile (see [comment from @csadorf](https://github.com/glotzerlab/signac/issues/171#issuecomment-583296803)) but a simple solution is fine for now.

**Comment by vyasr** [comment]
Since it's not API breaking, I agree with you that we could in principle just remove it. However, on the off chance that anyone is actually taking advantage of the rapidjson integration it would be interesting to know, because that would provide some data on whether #171 is ever worth pursuing or not. From that point of a view, a deprecation warning (with a note to contact us if it shows up) might be nice.

**Comment by csadorf** [comment]
I agree with @bdice , let's just remove it. Adding some kind of deprecation cycle adds a lot of unnecessary work that is likely not worth it. For users who relied on this, this will represent a regression, not an API breaking change. If this is very crucial to some users they are just as  likely to complain in that case, compared to explicitly deprecating it. After it's removed we can have a look at it refactoring to make it possible to enable this in the future.

**Comment by bdice** [comment]
Next steps for a pull request:
- Remove rapidjson from core/json.py.
- Remove CI testing for rapidjson.
- Search for “rapidjson” in the code base and make sure nothing was missed.

**Comment by ac-optimus** [comment]
hi, @bdice can I work on this issue?

**Comment by CryoZEUS** [comment]
I'd like to work on this issue as well if that is okay?

**Comment by bdice** [comment]
@CryoZEUS I think one person should be able to do these tasks -- it's a small set of changes. If you would like to be added as a reviewer once @ac-optimus creates a pull request, we can do that! Thanks for offering to help. 😄

**Comment by bdice** [comment]
@ac-optimus I searched the code for "rapidjson" and I have confirmed that the two changes I suggested (remove from core/json.py and remove CI testing) are all that is needed for this pull request. That's all you will need to do.

**Comment by CryoZEUS** [comment]
@bdice Sure. Can you suggest any **good first issue** that doesn't involve documentation? I'm willing to contribute and still going through the repo; but not sure how I could get started.

**Comment by bdice** [comment]
@CryoZEUS I'll tag you on a signac-flow issue soon! I haven't made the issue yet but I think it would be a good first issue. Thanks for your interest!

**Comment by CryoZEUS** [comment]
@bdice That would be really great! Thank you! :)

**Comment by ac-optimus** [comment]
> @ac-optimus I searched the code for "rapidjson" and I have confirmed that the two changes I suggested (remove from core/json.py and remove CI testing) are all that is needed for this pull request.

done!
