### ISSUE TITLE
Add option to hide constant parameters with signac statepoint

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/signac#290]
### Feature description

It would be nice to be able to hide constant parameters when calling `signac statepoint` on the command line, similar to the way you can do `$ signac schema -x` or `schema = project.detect_schema(exclude_const=True)`.

### Proposed solution

```bash
# full schema
$ signac schema
{
 'x': 'int([0, 1, 2], 3)',
 'y': 'int([2], 1)',
}

# hide constant params
$ signac schema -x
{
 'x': 'int([0, 1, 2], 3)',
}

# show all sp params for job abc123
$ signac statepoint abc123 -p
{'x': 1,
 'y': 2}

# this is the functionality that I want
$ signac statepoint abc123 -p -x
{'x': 1}
```
I assume the machinery is already in the code to make this possible since it is an option to `detect_schema`. I'm also assuming this will be a fairly quick and easy change, which I'm happy to implement given just a touch of guidance.

**Comment by csadorf** [comment]
I like the idea and should be straightforward to implement, however it must be clear that using the `-x` option will significantly increase the runtime of this particular command especially if state points are not cached.

The state point subcommand is implemented here: https://github.com/glotzerlab/signac/blob/7ba32136abd4480d558aea46fe0400c142ec4912/signac/__main__.py#L266

You should then detect the schema for the project with constant keys ignored

https://github.com/glotzerlab/signac/blob/7ba32136abd4480d558aea46fe0400c142ec4912/signac/contrib/project.py#L554

and then simply reduce the displayed state point to the intersection of state point and schema keys. There might be a bit of added complexity with nested state points, but we can look at that when it becomes relevant.

**Comment by b-butler** [comment]
@tcmoore3 are you interested in implementing this feature?

**Comment by mikemhenry** [comment]
@bdice this may be a good issue to work on  for office hours or direct someone too

**Comment by csadorf** [comment]
@tcmoore3 Any update on this?

**Comment by tcmoore3** [comment]
No update. It doesn't seem like anyone else has any interest, so I'm OK with labelling as `wontfix` and closing.
