### ISSUE TITLE
Reduce test noise due to deprecation warnings

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#291]
### Description

Switching to pytest as the primary testing framework has vastly increased the noise for test outputs due to deprecation warnings. The noise should be reduced analagous to how this was handled for signac-flow, here: https://github.com/glotzerlab/signac-flow/pull/246

### To reproduce

Execute the test framework with `pytest` within the repository root directory.

**Comment by ac-optimus** [comment]
hi @csadorf can i work on this issue?

**Comment by csadorf** [comment]
@ac-optimus Absolutely! Please let me know if you have any questions.

**Comment by ac-optimus** [comment]
> @ac-optimus Absolutely! Please let me know if you have any questions.

yes sure!

**Comment by vyasr** [comment]
Resolved by #292
