### ISSUE TITLE
Implement the CLI with Click instead of argparse

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#297]
### Summary

Implement the command line interface (CLI) with the [Click library](https://click.palletsprojects.com/) instead of [argparse](https://docs.python.org/3/library/argparse.html).

### Motivation

Using Click for the implementation of a CLI has numerous advantages over using argparse, including a more concise API, the enforcement of a more consistent interface, and built-in support for the implementation of test runners. In addition, the library comes with a collection of helper functions and tools, that are relevant for CLI development. Please see [this page](https://click.palletsprojects.com/en/7.x/why/) for a more comprehensive overview of why one would want to implement a CLI with Click.

### Proposed plan for implementation

Since this is a larger refactoring project, it should be executed in stages. Each stage should be introduced as a separate pull request:

- [x] Ensure that the coverage of `signac/__main__.py` is measured, see instructions [here](https://coverage.readthedocs.io/en/coverage-5.0.3/subprocess.html).
- [x] Review existing unit tests for `signac/__main_.py` and implement missing tests to reach a test coverage of at least 80%.
- [ ] Refactor the CLI implementation, replacing argparse with Click _exclusively_ for the 'find' sub command; mark all unit tests for other sub-commands as expected failures. Once the `find` sub-command was successfully refactored, refactor all other sub-commands. Replicate the unit tests for each command found in `tests/test_shell.py` in a seperate test module called `tests/test_main.py` with Click's[ built-in test runner](https://click.palletsprojects.com/en/7.x/testing/). The original tests may not fail!

### Risks

It is very likely that not all sub-commands can be implemented in the exact same way as before, because Click imposes some restrictions that argparse does not. These restrictions will likely improve the consistency and quality of the CLI, but make it a bit more difficult to create an exact replacement and may require the introduction of some minor backwards incompatibilities.

**Comment by csadorf** [comment]
@vishav1771 Would you be interested in giving this a shot?

**Comment by vishav1771** [comment]
Sure :+1:

**Comment by csadorf** [comment]
> Sure

Awesome, thx! Please feel free to discuss questions about this project directly on this issue. Please apply the "Click" label to any PRs related to this issue so that it is easier for us to keep track of things.

**Comment by bdice** [comment]
@vishav1771 Thanks for taking this on! Eventually we will want to do the same for signac-flow, so it may be helpful to document the steps you take along the way for a contributor to do this again for that package.

**Comment by vishav1771** [comment]
To measure coverage of `signac/__main__.py`:  pytest provides [pytest-cov](https://pypi.org/project/pytest-cov/) extension which can replace `coverage.py`. Should I go with this?

**Comment by vyasr** [comment]
I think using pytest-cov is a good idea. We will probably want to use `click.testing` for actually writing future tests.

**Comment by csadorf** [comment]
I unlinked #300 again, because merging that PR will not fully close this issue.

**Comment by csadorf** [comment]
I've marked the first two tasks as completed with the merge of #300 . Nice job @vishav1771 !
