### ISSUE TITLE
Ability to clone a signac project

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac#304]
### Feature description

We currently have the ability to clone jobs between signac projects. It could be useful to clone projects wholesale.

### Proposed solution

Here's a [script](https://gist.github.com/vyasr/590ba0eb2e221f98dbd200b7539ebac8) showing how this could be accomplished. It's taken from our outdated [signac-utils repository](https://bitbucket.org/glotzer/signac-utils/src/master/bin/flow-clone).

### Additional context

It's unclear if there is a need for this feature, but since it's the only script in the signac-utils repository that hasn't already been directly included into signac it's worth having this for bookkeeping in case a need arises.

**Comment by kidrahahjo** [comment]
Hi @vyasr 
If it's not very urgent to resolve this, can I try my hands in this?

**Comment by bdice** [comment]
@kidrahahjo I am not sure if this has a clear use case. At least, I couldn't see a case where I would prefer this solution over just using normal command line tools for downloading/extracting/copying files. I agree with @vyasr that we needed to open this issue for bookkeeping / not forgetting that the feature was once developed. The fact that we forgot about it for years means it's probably not an important feature. If we want this in the future, we can re-open this issue. I vote to close this issue with no action taken.
