### ISSUE TITLE
project.detect_schema() should have a pretty representation in IPython

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#314]
### Feature description
In #127, we added an IPython representation for `JobsCursor` objects. I would like the same kind of behavior for `ProjectSchema` objects, with a pretty format that looks similar to the output of `signac schema`.

### Proposed solution

Add a method `_repr_html_` to `ProjectSchema`. Refer to `JobsCursor` and `Project` classes for examples.

**Comment by vishav1771** [comment]
@bdice  I like to work on this.

**Comment by vyasr** [comment]
Sure!

**Comment by vishav1771** [comment]
I have added the `_repr_html` for `ProjectSchema`. It's looking like this now:

![Screenshot (4)](https://user-images.githubusercontent.com/46069089/78924636-cd49ef80-7ab7-11ea-80de-57c0e3e2fb9e.png)

Is this what we are looking for. Should I continue with the PR.

**Comment by bdice** [comment]
@vishav1771 Yeah, that seems like a great start! I can provide more comments when you create the PR.
