### ISSUE TITLE
Unexpected errors when using ints as keys for JSONDict

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/signac#316]
### Description

I'm trying to go through a project and save calculation results into a `JSONDict`. The basic schema is just 2 statepoint parameters, say `p1` and `p2`. I create a `JSONDict` `dd`, and call `dd.setdefault(p1, {})`. I then get a `KeyError` when I try to access `dd[p1]`. This error only happens with `p1` is an int or float; I get the expected behavior when it is a string.

It seems like there is an issue saving the dict when I have a non-str key.

### To reproduce
This example show

```shell
>>> import signac
>>> import os; os.system('rm test.json')
>>> x = signac.JSONDict('test.json')
>>> y = x.setdefault(1, {})  # note: key is int
>>> z = y.setdefault(2, {})
>>> z['c'] = 1
>>> print(x)
{'1': {}}

>>> import signac
>>> import os; os.system('rm test.json')
>>> x = signac.JSONDict('test.json')
>>> y = x.setdefault('1', {})  # note: key is str
>>> z = y.setdefault('2', {})
>>> z['c'] = 1
>>> print(x)
{'1': {'2': {'c': 1}}}
```

In the first case, `json.dict` has the contents `{'1': {}}`, so it doesn't look like the syncing is actually happening in that case.

### System configuration

```
$ python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__)'
Darwin-17.7.0-x86_64-i386-64bit
3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
1.2.0
```
and
```
$ python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__)'
Darwin-17.7.0-x86_64-i386-64bit
3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
1.3.0
```

**Comment by mikemhenry** [comment]
We will throw a warning if a user tries to use an `int` as a key since `int` keys are not supported in JSON.
