### ISSUE TITLE
Unify or improve consistency between groupby and groupbydoc

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac#328]
@vyasr @zhou-pj I looked at the [original pull request](https://bitbucket.org/glotzer/signac/pull-requests/26/groupby/diff) where we introduced this feature. I don't recall discussing this API choice explicitly. I think it was an arbitrary choice that allowed `groupby` to be very general (a callable of `job` is more flexible than a callable of `job.sp`) while allowing `groupbydoc` to have `job.doc` as the argument for convenience. The most "parallel" solution would be to have `groupby` operate on `job.sp` in all cases but it would not be useful for cases where you want to group by something like `job.isfile('output.txt')`.

_Originally posted by @bdice in https://github.com/glotzerlab/signac/pull/323#issuecomment-617351512_

**Comment by vyasr** [comment]
@bdice @zhou-pj I honestly think the current API is kind of confusing. We could unify the two by changing to just a single `groupby(sp=None, docs=None, keyfun=None)` (or whatever arg names), but I see the ugliness that probably prevented you from doing that originally since it's nicer to have a single argument. What if any key prefixed with "doc." was treated as a doc key, and others are statepoint keys (if strings are passed)? There's precedent for that, for instance in signac-dashboard's search bar. Then we could deprecate `groupbydoc` and just have one function.

**Comment by csadorf** [comment]
I was hoping that we could revise the search-functionality in general and have the option to provide a unified filter, where the `sp.` prefix is implicit. This would also help with other applications such as dashboard. I even implemented a prototype for this: #188

**Comment by vyasr** [comment]
Ah yes OK I reference dashboard because I thought something like this existed but couldn't find it. That's a very helpful find, I definitely think that's worth looking back into.

**Comment by mikemhenry** [comment]
This is being worked on in #332
