### ISSUE TITLE
Expose more h5py functionality for dataset creation, chunking, etc.

### ISSUE THREAD

**Issue by klywang** [glotzerlab/signac#335]
### Feature description

There are certain cases where I would prefer to initialize an array for an entire simulation (ie `MxNxd` a matrix where `M` is the number of frames, `N` is the number of particles and dimensionality of parameter associated with each particle). Initializing these arrays using `numpy.zeros` or `numpy.empty` can be memory intensive and I would like to avoid appending arrays at each frame or importing switching between `h5py` and `signac` data API. 

### Proposed solution

Either exposed `h5py.create_dataset` in `signac` or create a functions associated with `H5Store` class called something like `create` and `resize`. It should take in the `size` and  `chunk` (optional) as additional arguments, where `size` is the total size of the data and `chunk` is the size of the data to be loaded into memory at a given time/stored together.

**Comment by bdice** [comment]
@klywang I could see this working just fine. Following the [h5py.create_dataset API here](http://docs.h5py.org/en/stable/high/dataset.html#creating-datasets), I think you would want to add a method to the [H5Group class](https://github.com/glotzerlab/signac/blob/master/signac/core/h5store.py#L182) that is something like this:

```python
    def create_dataset(self, *args, **kwargs):
        """Create a new dataset.

        See :py:meth:`h5py.Group.create_dataset` for arguments.
        """
        return self._group.create_dataset(*args, **kwargs)
```

We may wish to copy more of the Group API as well. Complete Group API reference linked here for convenience: http://docs.h5py.org/en/stable/high/group.html#Group

**Comment by b-butler** [comment]
@klywang are you interested in implementing the solution Bradley mentioned above?

**Comment by klywang** [comment]
Yeah I can do that

**Comment by vyasr** [comment]
Rather than mirroring the API, why not directly expose `H5Group._group`? If see value in direct access to more h5py APIs than just `create_dataset`, I think the proper solution would be to make that a public attribute that users could directly work with if they would like. We already expose `H5Store.file`, I don't see any reason not to do that for groups.
