### ISSUE TITLE
Automate Version Bumping With Dependabot

### ISSUE THREAD

**Issue by mikemhenry** [glotzerlab/signac#338]
[Dependabot]( https://help.github.com/en/github/administering-a-repository/about-github-dependabot) can automatically a repo for the dependencies that exist, check if new versions exist, then open PRs to test and see if anything breaks. The bot also includes the release notes of the package as well, so a reviewer would need to skim the release notes to make sure there isn't anything in them that is important, then ensure that the tests pass before merging. The bot has commands to ignore a version as well as a dependency. To see an example, I've set it up on my fork here:
https://github.com/mikemhenry/signac/pulls
I set the bot up to update everything but set the max number of open PRs to 10. We could set it to only update if there are security updates if we want.

**Comment by bdice** [comment]
@mikemhenry This is cool. I see no reason not to enable it. I have performed those updates by hand before. It looks like you can configure updates to happen once a month, which I would prefer just to keep the noise down. Do we have consensus on this, @glotzerlab/signac-maintainers?

**Comment by mikemhenry** [comment]
Cool, I will open a PR with the settings of once per month + no more than 10 open PRs by the bot to keep from generating too much noise.
