### ISSUE TITLE
The flake8 pre-commit hook is deprecated

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#355]
### Description

Contributors are advised to install the flake8 pre-commit as described [here](https://docs.signac.io/en/latest/community.html#contributions).
However, this particular hook is [deprecated](https://gitlab.com/pycqa/flake8/-/issues/568).

### To reproduce

Try to install the hook with:
```
flake8 --install-hook git
```
Which will trigger a deprecation warning.

### Error output

```
WARNING: flake8 vcs hooks integration is deprecated and scheduled for removal in 4.x.  For more information, see https://gitlab.com/pycqa/flake8/issues/568
```

### Proposed solution

Switch to [pre-commit](https://pre-commit.com/).

**Comment by csadorf** [comment]
This is also an opportunity to improve our setup to automatically linters etc.

**Comment by bdice** [comment]
I can vouch that pre-commit is a nice tool. 👍

**Comment by mikemhenry** [comment]
It would be nice to include doc style linting as part of that pre-commit hook that can parse our config file for doc style.

**Comment by kidrahahjo** [comment]
Should I work on this one to set up the automatic pre-commit hook?

**Comment by bdice** [comment]
@kidrahahjo This would be great to do after we merge #357 because then we can set up the pydocstyle linter as well. If you want to get started sooner, you can just run flake8.

As a related issue, we should refactor our CI so that it uses `requirements-dev.txt` to install the linters, for ensuring consistent versions.

**Comment by csadorf** [comment]
@kidrahahjo I think that would be great if we could get this prepared! We can always update the linter configuration after #357 is merged.

**Comment by kidrahahjo** [comment]
@csadorf 
Just to be sure, should I use hooks from `black` or `autopep8`? Or should I just use the hooks provided by `pre-commit`?

**Comment by bdice** [comment]
@kidrahahjo Use the same checks that are on our CI. flake8, pydocstyle, mypy. https://github.com/glotzerlab/signac/blob/master/.circleci/config.yml#L19-L37

**Comment by kidrahahjo** [comment]
@bdice  The `flake8` check fails as it commits even when it catches an error. I think the hook is bugged and that's why it's deprecated.
