### ISSUE TITLE
Group CLI documentation to help newer users

### ISSUE THREAD

**Issue by cbkerr** [glotzerlab/signac#360]
### Motivation

The long list of CLI tools added in #359 is helpful but could be daunting to new users.

The full list of commands is: init,project,job,statepoint,diff,document,rm,move,clone,index,find,view,schema,shell,sync,import,export,update-cache,config

### Possible Solution

Breaking down the list of 19 commands into groups corresponding to user mindset or experience level could help new users know what commands to start with. @atravitz and I began discussing possible grouping strategies.

Note that to allow advanced users to quickly search for them on the web page, commands should never be hidden behind a category .

Some grouping ideas include: project lifecycle, basic vs advanced usage (where advanced=infrequent means 'always go to the docs for it'), or project tasks. I think one constant is having some form of an "advanced/rarely used" category to get those out of the way. One challenge for us is that new users have different mindset than we non-new users.

Let's open a discussion on what categories to use and where to place commands. We can always change names of categories.

## Options
I've tried categorizing the commands into two possible groupings (1 and 3). I don't know how to categories the commands based on option 2.

### Option 1: Project Lifecycle
Option 1 looks unbalanced, I think because it's not clear where the "advanced" category is:

**Managing a Project**
job
statepoint
find
diff
shell
schema
**Modifying a Project**
init
project
document
rm
move
clone
index
sync
update-cache
**Sharing/Receiving**
view
import
export

### Option 2: Frequency of Use (commands not categorized)
Option 2 could be best to on-board new users, but I don't know how to distinguish between frequent and occasional usage.

**Start Here**
**Occasional Use**
**Advanced Use**

### Option 3: User Mindset
I like option 3 because it has basic and advanced commands but divides basic commands into what you might do when poking around a project vs. actively working on one.

**Exploring a Project**
schema
find
statepoint
diff
document
view
**Working on a Project**
job
shell
sync
clone
move
rm
**Rare Use**
init
project
index
import
export
config
update-cache

**Comment by bdice** [comment]
Great idea! A few notes:
- I like the "Lifecycle" approach a lot more than the latter two proposals. It matches how I categorize them in my head.
- We should include an rST rubric in this page, at the top. It acts like a set of quick links or "Table of Page Contents". That's helpful regardless of how the content is organized.
- I would suggest the subtitle "Sharing and Archival" for the last category with view, import, export.

**Comment by pepak13** [comment]
I like the Lifecycle approach. Generally when I using a new package or software and when I'm going through a documentation, I'll try to aim my search to relevant categories. So this fits in with that. I'm sure that this is a common approach anyway.

**Comment by atravitz** [comment]
I agree with option 1 (but I think I also proposed it, so I may be biased). I think it also helps users understand right off the bat the three types of things you can do from the command line.

**Comment by cbkerr** [comment]
After enough time away to have fresh eyes on this, I can agree on the groupings more aligned with my option 1. I still don&rsquo;t like how imbalanced it is, so I&rsquo;ve moved to categories that better fit them.

I&rsquo;ve also tried to rearrange the commands *within* each category based on frequency of use and create logical progression with similar commands nearer each other (like `statepoint` and `diff`; `export` and `import`; `clone` and `sync`).

Here are some thoughts on how I applied the categories:
* I think of the commands in **Managing a project** as daily interactions, so I propose renaming it to **Interacting with a project**.
* I think of **Modifying a project** as one-off config stuff but within the same project schema.
* **Sharing and Archival** is when done working on project or when switching to a new project schema or involving multiple projects.

## New categorizations
**Interacting with a project**
find
statepoint
diff
document
schema
shell
**Modifying a project**
init
config
project
job
rm
index
update-cache
**Sharing and Archiving**
view
export
import
move
clone
sync

If we can&rsquo;t agree within a few weeks, I suggest arranging alphabetically.

Also, the documentation for many of these commands doesn&rsquo;t list what they do (making them hard to categorize perhaps), but that&rsquo;s for another issue&#x2026;

**Comment by bdice** [comment]
@cbkerr I recommend making a pull request for these changes before we dive any deeper on this issue. A perfect organization of the commands is not useful unless implemented in the docs. That said, I would make the following minor rearrangements.

- Re-order "document" so it's below "statepoint"
- Keep "move, rm, clone" next to each other in "Modifying a project"
- Move "index" to "Sharing and Archiving"

**Interacting with a project**
find
shell
schema
statepoint
document
diff
**Modifying a project**
init
config
project
job
move
rm
clone
update-cache
**Sharing and Archiving**
view
export
import
sync
index

**Comment by tcmoore3** [comment]
See also #412.

@cbkerr Any progress on this?

**Comment by cbkerr** [comment]
From the limited documentation, I kept `move` and `clone` apart from `rm` because only the first two deal with multiple projects while `rm` stays within one project. @bdice what was your reason for putting them together?

**Comment by bdice** [comment]
Those commands are roughly equivalent to `mv`, `cp`, `rm`, which seem like related "modifying" utilities to me.
