### ISSUE TITLE
dot formatting bug in sync diff

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac#375]
### Description

When syncing two dicts, the synchronization error message reports key values incorrectly, as shown below.

### To reproduce

I'm currently working on writing a test to replicate this error.

### Error output

![image](https://user-images.githubusercontent.com/31974495/89965605-346ce180-dc1b-11ea-8582-a56db93500c3.png)

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: macOS
 - Version of Python [e.g. 3.7]: 3.8.1
 - Version of signac [e.g. 1.0]: 1.4.0

Or copy & paste the output of: `python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__)'`

**Comment by atravitz** [comment]
update: while trying to write a test to reproduce this, it looks like `ProjectSyncTest()` isn't being called by pytest. I'm not sure why this is happening - does anyone more familiar with pytest have thoughts?

**Comment by bdice** [comment]
@atravitz The [pytest naming conventions](https://docs.pytest.org/en/reorganize-docs/new-docs/user/naming_conventions.html) say we should probably rename `ProjectSyncTest` to `TestProjectSync` for it to be recognized and executed as a test.

**Comment by atravitz** [comment]
@bdice got it, thanks! It turns out this is just a command line error. do we have tests for CLI?

**Comment by bdice** [comment]
@atravitz Can you provide more information? I'm trying to reproduce this and I'm not sure what the screenshot says (it's cut off). Are there specific requirements about the job state points or document values?

**Comment by bdice** [comment]
Here is a minimal-ish reproduction.

```bash
#!/bin/bash

rm -rf project_a project_b

mkdir -p project_a
cd project_a
signac init project_a
signac job --create '{"apple": 1}'
signac job --create '{"apple": 2}'
cd ..

mkdir -p project_b
cd project_b
signac init project_b
signac job --create '{"apple": 1}'
signac job --create '{"banana": 2}'
cd ..

signac sync project_a project_b
```
