### ISSUE TITLE
H5Store support for string arrays

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#419]
### Feature description

I am unable to store string arrays in an H5Store. I would like to be able to store and retrieve NumPy `U` typed arrays (Unicode).

Currently this happens:

```python
>>> job.data['strings'] = np.array(['A', 'Bbb'])
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "/.../signac/signac/core/h5store.py", line 460, in __setitem__
_h5set(self, self._file, self._validate_key(key), value)
File "/.../signac/signac/core/h5store.py", line 115, in _h5set
grp[key] = value
File "/.../python3.8/site-packages/h5py/_hl/group.py", line 411, in __setitem__
ds = self.create_dataset(None, data=obj)
File "/.../python3.8/site-packages/h5py/_hl/group.py", line 148, in create_dataset
dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
File "/.../python3.8/site-packages/h5py/_hl/dataset.py", line 89, in make_new_dset
tid = h5t.py_create(dtype, logical=1)
File "h5py/h5t.pyx", line 1629, in h5py.h5t.py_create
File "h5py/h5t.pyx", line 1653, in h5py.h5t.py_create
File "h5py/h5t.pyx", line 1719, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U3')
>>> 
```

h5py explicitly does not support `U` data types: https://docs.h5py.org/en/stable/strings.html#what-about-numpy-s-u-type
> NumPy also has a Unicode type, a UTF-32 fixed-width format (4-byte characters). HDF5 has no support for wide characters. Rather than trying to hack around this and “pretend” to support it, h5py will raise an error if you try to store data of this type.

#### User-space solution:
Handle encoding and decoding of string arrays manually with [np.char.encode](https://numpy.org/doc/stable/reference/generated/numpy.char.encode.html) and [np.char.decode](https://numpy.org/doc/stable/reference/generated/numpy.char.decode.html).

#### Potential "convenience" solution in signac:
As described in the h5py docs, there really isn't a good way to handle this problem without any potential downsides / risk of unexpected data conversion. Here's my best attempt thus far, with negative impacts noted. **The strategy of this approach would be to sacrifice some level of user control over encoding and exotic data types in exchange for convenience in "common" operations with _string/byte_ storage and retrieval.** This is a markedly different approach than h5py takes, but is in line with some design decisions in the existing H5Store implementation (e.g. pandas support, existing string handling).

- Convert Unicode string arrays (dtype `U`) to UTF-8 encoded arrays of bytes before storing (data is provided to h5py with dtype `S`).
- Interpret all _arrays of bytes_ (returned with dtype `S` from h5py) as UTF-8 encoded text that is returned as a NumPy `U` array.
  - Downside: This is backwards-incompatible if users have previously stored raw bytes as `S` arrays.
  - Downside: Incompatible with non-UTF-8 encodings (ASCII would still be valid: ASCII is a strict subset of UTF-8).
- To preserve the ability to store arrays of bytes, the data can be wrapped with NumPy's `void` type (dtype `V`).
  - Example: `np.void(np.array(['abc', '123'], dtype=np.string_))`
  - Potential benefit: Storing raw bytes as `void` arrays (treated as the type HDF5 OPAQUE) is actually recommended by h5py, to avoid conflicts with data being interpreted as strings.
  - Potential downside: Existing void-typed arrays would be returned with dtype `S` instead of `V`.

| Input Data        | Current storage | Current retrieval | Proposed storage | Proposed retrieval |
|-------------------|-----------------|-------------------|------------------|--------------------|
| String arrays (U) | Error           | Not possible      | UTF-8 bytes (S)  | String array (U)   |
| Byte arrays (S)   | Bytes array (S) | Bytes array (S)   | UTF-8 bytes (S)  | String array (U)   |
| Void arrays (V)   | Void (V)        | Void (V)          | Void (V)         | Bytes array (S)    |

### Additional context

In #411, I added a wrapper that allows h5py >=3.0.0 to store/retrieve individual strings (not arrays). String behavior was changed in h5py 3. Any solution should be designed to work for both h5py 2 and h5py 3, which should be possible.

**Comment by mikemhenry** [comment]
This is a tricky problem. We could add a recipe for your proposal, and then catch the error and point the user to docs/this issue in the meantime.

**Comment by vyasr** [comment]
Perhaps a simpler alternative that is more in line with how we handle numpy arrays and non-str keys in JSONDicts (although the latter will be removed in signac 2.0) is to just encode numpy arrays of type 'U' so that storing and reading works, but users will have to decode when loading the data back in. We can also warn when encoding happens to alert users that this is happening.
