### ISSUE TITLE
Deprecate syncutil.copytree

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#432]
### Refactor copytree

The file `signac/syncutil.py` defines a function called `copytree`. This is based on the Python 3 implementation of `shutil.copytree`. I think this was implemented as a compatibility layer for Python 2, which didn't accept the same options as in Python 3 (specifically `copyfunction`, which allows users to perform a "move" instead of a "copy", for instance). Now that we support only Python 3.6+, this should be refactored and removed.

### Proposed solution

1. Verify that the implemented function `signac.syncutil.copytree` matches the implemented behavior of `shutil.copytree`.
2. Deprecate the code for `signac.syncutil.copytree` and indicate that users should use `shutil.copytree` instead.
3. Change all implementations and documentation referring to `syncutil.copytree` to point to `shutil.copytree`. No behavior will change, and this should be fully API-compatible.

**Comment by shandave** [comment]
@bdice I want to contribute

**Comment by bdice** [comment]
@shandave I can assign you on this issue, please let us know if you have questions. Thanks!
