### ISSUE TITLE
Adding pre-commit hooks

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#436]
We might like to adopt some additional (simple) pre-commit checks from this list:

https://github.com/asottile/scratch/blob/master/.pre-commit-config.yaml

We also might like to use pre-commit’s auto-updater service (in beta).

**Comment by vyasr** [comment]
If you're interested in available hooks, there's also the [official list of supported hooks](https://pre-commit.com/hooks.html)

**Comment by mikemhenry** [comment]
Also see this PR in signac-flow
https://github.com/glotzerlab/signac-flow/pull/333

**Comment by tcmoore3** [comment]
This issue seems stale. Is there still interest in implementing more pre-commit hooks?

**Comment by bdice** [comment]
It’s not a priority, we can close this and re-visit if we have specific needs for hooks.
