### ISSUE TITLE
Use intersphinx in documentation

### ISSUE THREAD

**Issue by cbkerr** [glotzerlab/signac#452]
### Problem description
All external links use hardcoded links, as [pointed out](https://github.com/glotzerlab/signac/pull/444#discussion_r549435403) in #444. Some examples are in contrib/job.py and contrib/project.py

### Proposed solution
Switch to intersphinx.

For some pointers, see https://github.com/glotzerlab/signac-docs/wiki/How-to-cross-reference-links-between-package-docs-and-signac-docs-using-intersphinx

A model of a project that uses it already is signac-flow. Refer to these files for examples:
* [conf.py](https://github.com/glotzerlab/signac-flow/blob/6d0420788454368458e07da63a50bb58b88c70e5/doc/conf.py#L317) for what to add to the configuration
* [operations.py](https://github.com/glotzerlab/signac-flow/blob/6d0420788454368458e07da63a50bb58b88c70e5/flow/operations.py#L112) for an example of how to put in a reference

**Comment by tcmoore3** [comment]
@cbkerr What's the status of this issue?

**Comment by cbkerr** [comment]
@AlainKadar volunteered to take this on. I will mentor

**Comment by bdice** [comment]
I think this issue can be closed -- I took a look in signac and signac-flow, all of the `http` links that I saw are links that would appear to users on the command line and thus shouldn't be intersphinx references.
