### ISSUE TITLE
Improve test coverage of exception cases in job.py

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac#473]
In #472 @bdice requested improving coverage since that PR modifies various job internals. The relevant untested cases are not new, they are the same cases that are currently untested on master, so we should endeavor to address these on master first since that will be simpler to identify issues without having to deal with the complexities of the new synced collection infrastructure. Lines of code missing coverage can be see on [the Codecov page for job.py](see https://codecov.io/gh/glotzerlab/signac/src/master/signac/contrib/job.py).

**Comment by bdice** [comment]
One of these failure cases to test: try to edit a state point file that can't be moved because its directory is read-only. I think that will raise an error that isn't caught here. https://github.com/glotzerlab/signac/pull/472/files#diff-7ca53886bf1aa90f8bf61c441c23a33b6a7ac67d61adad647ee141f99d5deafaR105

**Comment by bdice** [comment]
Another failure case: failure to call `job.init()` because the `workspace` directory is read-only and a new job workspace directory cannot be created.

**Comment by mikemhenry** [comment]
A quick google didn't find anything, but I imagine there is a way to simulate disk I/O issues with pytest (such as a read only file system)

**Comment by bdice** [comment]
Most of these test cases should be possible to construct with just the `os` module.

**Comment by vyasr** [comment]
Still relevant
