### ISSUE TITLE
Rename FN_MANIFEST

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#478]
Suggesting this change for signac 2.0:
- `Job.FN_MANIFEST` and similar properties of Job/Project should be private.
- "Manifest" should be changed to "state point" universally in variable names and docstrings.
- e.g. `FN_MANIFEST` should be `_FN_STATE_POINT`.

**Comment by vyasr** [comment]
This issue was addressed by #610. Unless there's a reason to revisit the visibility of the attributes, I think we can close this. @bdice what do you think?

**Comment by bdice** [comment]
I'd still like to make these attributes private.
