### ISSUE TITLE
Key returning dict instead of SyncedAttrDict (PR 484)

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#485]
### Description
@vyasr I'm using PR #484 and noticed that signac-flow fails on some tests that rely on the project document's `_status` field. I'm accessing `self.document["_status"]` and it's returning a plain `dict` instead of a synced collection. I'm not sure what is causing it yet.

### To reproduce

Check out PR #484 (commit d2805494e639dc6fc80c8dd2874f92b326fa2871) and signac-flow master (commit 61f20a9969cfcaca554dd648497051afeb6380de). Then execute `pytest -x -k test_submit_status -s`.

**Comment by vyasr** [comment]
Resolved in #486
