### ISSUE TITLE
API break in JobsCursor

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#500]
### Description

PR #332 broke the public API of the `JobsCursor` constructor. The argument `doc_filter` was removed without deprecation or a major version increment.

### To reproduce

The latest release of signac-flow (0.12 or newer) relies on the public API of this class for its internal class `_AggregatesCursor`.

### Error output

```python
Using environment configuration: StandardEnvironment
ERROR: Encountered error during program execution: '__init__() takes 3 positional arguments but 4 were given'

Traceback (most recent call last):
  File "/home/bdice/code/signac-flow/flow/project.py", line 4821, in main
    args.func(args)
  File "/home/bdice/code/signac-flow/flow/project.py", line 4343, in _main_status
    aggregates = self._select_jobs_from_args(args)
  File "/home/bdice/code/signac-flow/flow/project.py", line 4544, in _select_jobs_from_args
    return _AggregatesCursor(self, filter_, doc_filter)
  File "/home/bdice/code/signac-flow/flow/project.py", line 286, in __init__
    self._jobs_cursor = JobsCursor(project, filter, doc_filter)
TypeError: __init__() takes 3 positional arguments but 4 were given
```

### System configuration

Please complete the following information:

 - Operating System: WSL Ubuntu
 - Version of Python [e.g. 3.7]: 3.8
 - Version of signac [e.g. 1.0]: 1.6 (3680496d2de604ba6d13c33ee60b71e58841f421)

**Comment by mikemhenry** [comment]
> those responsible have been sacked

**Comment by bdice** [comment]
You can take their jobs, but not their JobsCursors. 😂 Thanks for the help @mikemhenry.
