### ISSUE TITLE
piping doesn't work with signac find and signac statepoint on command line

### ISSUE THREAD

**Issue by bryaniswright** [glotzerlab/signac#565]
### Description

the issue is being caused when trying to pipe `signac find` into `signac statepoint` on command line. the expected behavior would be in the included example to return exactly 2 results. instead it returns all 6 jobs that exist.

### To reproduce
i am using https://github.com/cmelab/planckton-flow
which uses signac flow
i ran 6 jobs with the following statepoints:

```
{"input": ["ITIC-gaff"], "n_compounds": 3, "density": [0.05, "g/cm**3"], "e_factor": 1.0, "forcefield": "gaff-custom", "kT_reduced": 1.0, "tau": 1, "shrink_steps": 1000.0, "n_steps": 10000000.0, "dt": 0.0001, "remove_hydrogens": false, "mode": "gpu"}
{"input": ["CZTPTZITIC-gaff"], "n_compounds": 2, "density": [0.05, "g/cm**3"], "e_factor": 1.0, "forcefield": "gaff-custom", "kT_reduced": 1.0, "tau": 1, "shrink_steps": 1000.0, "n_steps": 10000000.0, "dt": 0.0001, "remove_hydrogens": false, "mode": "gpu"}
{"input": ["CZTPTZITIC-gaff"], "n_compounds": 3, "density": [0.05, "g/cm**3"], "e_factor": 1.0, "forcefield": "gaff-custom", "kT_reduced": 1.0, "tau": 1, "shrink_steps": 1000.0, "n_steps": 10000000.0, "dt": 0.0001, "remove_hydrogens": false, "mode": "gpu"}
{"input": ["CZTPTZITIC-gaff"], "n_compounds": 1, "density": [0.05, "g/cm**3"], "e_factor": 1.0, "forcefield": "gaff-custom", "kT_reduced": 1.0, "tau": 1, "shrink_steps": 1000.0, "n_steps": 10000000.0, "dt": 0.0001, "remove_hydrogens": false, "mode": "gpu"}
{"input": ["ITIC-gaff"], "n_compounds": 1, "density": [0.05, "g/cm**3"], "e_factor": 1.0, "forcefield": "gaff-custom", "kT_reduced": 1.0, "tau": 1, "shrink_steps": 1000.0, "n_steps": 10000000.0, "dt": 0.0001, "remove_hydrogens": false, "mode": "gpu"}
{"input": ["ITIC-gaff"], "n_compounds": 2, "density": [0.05, "g/cm**3"], "e_factor": 1.0, "forcefield": "gaff-custom", "kT_reduced": 1.0, "tau": 1, "shrink_steps": 1000.0, "n_steps": 10000000.0, "dt": 0.0001, "remove_hydrogens": false, "mode": "gpu"}
```
then on command line i ran `signac find n_compounds 1 | signac statepoint` and the output was all 6 statepoints instead of the 2 that matched n_compounds 1

if i saved the output of `x=$(signac find n_compouds 1)` to a variable in bash and then ran `signac statepoints $x` i get the expected behavior of only 2 statepoints

### Error output

<img width="768" alt="Screen Shot 2021-06-09 at 12 59 55 PM" src="https://user-images.githubusercontent.com/84930709/121413509-fb78c880-c922-11eb-8d5b-2a702dd4f4c8.png">

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: 
red hat linux 4.18.0-193.28.1.el8_2.x86_64

 - Version of Python [e.g. 3.7]: 3.7.10
 - Version of signac [e.g. 1.0]: 1.6.0
 - Version of signac-flow: 0.12.0

tagging @RainierBarrett @jennyfothergill

**Comment by bdice** [comment]
The desired behavior can be achieved by using the commands suggested here. Closing.
