### ISSUE TITLE
Remove --doc-filter from CLI

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#613]
### Feature description

From #586 conversation: https://github.com/glotzerlab/signac/pull/586#issuecomment-904777526

> Yes, I think --doc-filter should be removed in all cases. The signac-flow PR is less urgent since it only needs to go in before whichever flow version is the first to support signac 2.0, but adding the warning for find --doc-filter in this PR makes sense.

I decided to tackle this in a follow-up PR rather than extend #586.

### Proposed solution

`signac find --doc-filter ...` should be deprecated in 2.0 and removed in 3.0. A warning should be shown in signac 2.0.

`--doc-filter` should be deprecated and removed from signac-flow's CLI (e.g., `project.py status --doc-filter ...`).

**Comment by kidrahahjo** [comment]
I can take this up @bdice or we can add a good first issue label on this for others to try?

**Comment by vyasr** [comment]
I think this would be a good first issue to let someone else take on. IMO there are more complicated things that would benefit more from your expertise :)

**Comment by vyasr** [comment]
Based on recent discussions, this issue must be resolved for signac 2.0.

**Comment by vyasr** [comment]
Resolved in #795.
