### ISSUE TITLE
signac view CLI should not require a prefix

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#653]
### Problem
Specifying a path string to `$ signac view` requires the user to specify a prefix first, which defaults to `view`. This results in writing `signac view view path` which sounds awkward.

I frequently make this mistake and write `$ signac view path` instead of `$ signac view view path` (because that sounds silly). @cbkerr also ran across this while writing tests in #642.

### Proposed solution
This could be fixed in signac 2.0 by requiring `--prefix view` to use a prefix besides the default name `view`.

_Originally posted by @bdice in https://github.com/glotzerlab/signac/pull/642#discussion_r766929309_

<details>
<summary>CLI help message</summary>

```
$ python -m signac view --help
usage: __main__.py view [-h] [-f FILTER [FILTER ...]]
                        [-d DOC_FILTER [DOC_FILTER ...]]
                        [-j JOB_ID [JOB_ID ...]] [-i INDEX]
                        [prefix] [path]

Generate a human readable set of paths representing state points in the
workspace, e.g.
view/param_name_1/param_value_1/param_name_2/param_value_2/job. The leaf nodes
of this directory structure are symlinks (named "job") into the workspace
directory for that parameter combination. Note that all positional arguments
must be provided before any keyword arguments. In particular, the prefix and
path must be specified before arguments such as the filters, e.g. signac view
$PREFIX $VIEW_PATH -f FILTERS -d DOC_FILTERS.

positional arguments:
  prefix                The path where the view is to be created. Defaults to
                        view.
  path                  The path used for the generation of the linked view
                        hierarchy, defaults to '{{auto}}' (see
                        Project.export_to for information on how this is
                        expanded).

optional arguments:
  -h, --help            show this help message and exit

select:
  -f FILTER [FILTER ...], --filter FILTER [FILTER ...]
                        Limit the view to jobs matching this state point
                        filter.
  -d DOC_FILTER [DOC_FILTER ...], --doc-filter DOC_FILTER [DOC_FILTER ...]
                        Limit the view to jobs matching this document filter.
  -j JOB_ID [JOB_ID ...], --job-id JOB_ID [JOB_ID ...]
                        Limit the view to jobs with these job ids.
  -i INDEX, --index INDEX
                        The filename of an index file.
```

</summary>

**Comment by cbkerr** [comment]
I agree with your proposed solution because I've used that option to have several different views.

**Comment by bdice** [comment]
I think this might be a good first issue. I believe a solution may only require a couple changes:
https://github.com/glotzerlab/signac/blob/52ff01754cb9189ef67bedc664ce683cee4a75e0/signac/__main__.py#L1229-L1235

1. The line "prefix" should be changed to a flag instead of a positional argument, like "--prefix". I think that would make it optional (with the default value of "view" as before).
2. Update tests for the CLI.
 - Tests using the default value, like `signac view view path` should just say `signac view path`.

https://github.com/glotzerlab/signac/blob/52ff01754cb9189ef67bedc664ce683cee4a75e0/tests/test_shell.py#L207-L211

 - Tests using a non-default prefix should be added, and specify `--prefix`.

**Comment by srinathkp** [comment]
Hi @bdice , I'm new to signac project. Can I work on this ?

**Comment by bdice** [comment]
@srinathkp Sure! You'll want to create a fork of this repository and start your work from the `next` branch (which will become signac 2.0). Please feel free to post here if you have questions.

**Comment by vyasr** [comment]
@srinathkp are you still interested in looking at this? If not, @cbkerr do you want to take a stab at it? We should make this change (on next) prior to 2.0 since it is an API break.

**Comment by srinathkp** [comment]
No @vyasr . You can assign it to @cbkerr if he's interested.

**Comment by kodyt** [comment]
Hi all. I started looking at this syntax issue, but I am a little unfamiliar with argparse and signac. We can change the "prefix" to "--prefix" like you mentioned before and add "-p" for shorthand notation to make this an optional argument. @bdice Is this all you meant by making it a flag?

https://github.com/glotzerlab/signac/blob/52ff01754cb9189ef67bedc664ce683cee4a75e0/signac/__main__.py#L1229-L1235

Also,  I was wondering how I would go about testing this change. Would it be similar to `test_view_incomplete_path_spec`?

https://github.com/glotzerlab/signac/blob/52ff01754cb9189ef67bedc664ce683cee4a75e0/tests/test_shell.py#L196-L212

**Comment by vyasr** [comment]
@kodyt apologies for the slow response, yes your suggestion looks about right! Changing the name of the parameter in `add_argument` to include `--` will make it into a flag instead of a "positional" argument. And the test you pointed out is a reasonable choice for a template. You'll have to change the actual view commands that are called and make sure that the right directories are generated.
