### ISSUE TITLE
Use `id_` instead of `_id`.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#679]
@vyasr [noted](https://github.com/glotzerlab/signac/pull/667#discussion_r805197076) that we use `_id` instead of `id_`: "A subsequent underscore is a more canonical way to avoid shadowing builtins, as opposed to a preceding underscore indicating a private variable."

I agree with making this change across our entire codebase in a single PR on the `next` branch before the 2.0 release. We are currently consistent about using `_id` everywhere.

For context, this is to avoid shadowing the builtin [`id`](https://docs.python.org/3/library/functions.html#id) even though `_id` disagrees with [PEP8's naming conventions](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) which would indicate to use `id_`.

**Comment by ParisaTork** [comment]
Happy to do this for you, if you'd like?

**Comment by bdice** [comment]
Hi @ParisaTork! Sure, a pull request with this change would be helpful. This is a pretty straightforward find/replace change of existing variables named `_id`, which should be named `id_` instead. The changes should be made on the `next` branch, and the PR should target the `next` branch. You can tag me (@bdice) as a code reviewer (some other project contributors will also be tagged as reviewers automatically). You can see our [contributing guide](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md) and [this page in our docs](https://docs.signac.io/projects/core/en/latest/support.html#code-contributions) for information on making code contributions. Reach out if anything is unclear, we're always happy to improve the docs for new contributors.

**Comment by ParisaTork** [comment]
Hi @bdice - great, I'll sort that for you now!

**Comment by ParisaTork** [comment]
All sorted :) - didn't give me the option to add you @bdice as a reviewer but the PR is up for review: https://github.com/glotzerlab/signac/pull/680

**Comment by Onkar627** [comment]
Could you assign this issue to me?

**Comment by vyasr** [comment]
Resolved in #717
