### ISSUE TITLE
Use FutureWarning to report deprecations

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac#687]
### Feature description

It would be nice if warnings about the use of deprecated features were actually visible to users. Currently we generally throw `DeprecationWarning` in those scenarios, and Python hides these by default. The problem is exacerbated by the fact that the `deprecation.deprecated` decorator throws (a subclass of) `DeprecationWarning`.

### Proposed solution

1. We should change all of our manual warnings of deprecations to use FutureWarning instead of DeprecationWarning.
2. We should vendor a patched version of the `deprecation` package that uses `FutureWarning` instead of `DeprecationWarning`. Alternatively, we could make a PR to add support for this feature; the package seems to be in maintenance mode but did accept a PR from @bdice last year so we may be able to get the change made on a reasonable time scale.

**Comment by bdice** [comment]
An alternative to vendoring and altering the `deprecation` package would be to create a wrapper around `deprecation.deprecated` that converts `deprecation.DeprecatedWarning` to a `FutureWarning`. This is an example with a context manager, which would need to be converted to a decorator that forwards `*args, **kwargs` to the `deprecation.deprecated` decorator:

```python
from contextlib import contextmanager
from deprecation import deprecated, DeprecatedWarning
import warnings


@contextmanager
def future_deprecation(*args, **kwargs):
    with warnings.catch_warnings(record=True) as ws:
        yield
    # Show warnings as they occurred during the function call,
    # except change instances of DeprecatedWarning to FutureWarning.
    for w in ws:
        warnings.showwarning(
            message=w.message,
            category=FutureWarning if issubclass(w.category, DeprecatedWarning) else w.category,
            filename=w.filename,
            lineno=w.lineno,
            file=w.file,
            line=w.line,
        )


@deprecated(details="Please use operator.add instead.")
def plus(a, b):
    return a + b

```

**Comment by Akhil-Sharma30** [comment]
@bdice @vyasr in the codebase there some `DeprecationWarning` still present do I need to replace them `FutureWarnings`

**Comment by csadorf** [comment]
I would recommend the `common/` subpackage, because we might want to use the same vendored deprecation package in other signac packages, such as signac-flow.

**Comment by bdice** [comment]
I created https://github.com/glotzerlab/signac/pull/716 to vendor `deprecation`. Feel free to review! 👍

**Comment by vyasr** [comment]
@bdice can we close this issue now, or are there still outstanding DeprecationWarnings that we need to get rid of.

**Comment by bdice** [comment]
Ah, yes! This can be resolved now. I thought there was another task to complete, but it looks like we've completed this.
