### ISSUE TITLE
Deprecate either implicit or explicit initialization of jobs

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#71]
**[Original report](https://bitbucket.org/glotzer/signac/issue/71) by Carl Simon Adorf (Bitbucket: [csadorf](https://bitbucket.org/csadorf), GitHub: [csadorf](https://github.com/csadorf)).**

----------------------------------------

# About

In general all jobs require an *explicit* initialization with a call to `job.init()`, however there are two exceptions, where jobs are *implicitly* initialized:

 1. Switching into the workspace with `with job:`,
 2. Writing data to the `job.document` or `job.doc` attribute.

This is very confusing to beginners.
Jobs should either always be *explicitly* or *implicitly* initialized.

# Reasoning

**Backwards compatibility is very important**, however I would argue that this particular design choice is important enough to warrant an API break.
The `job.init()` method was introduced within one of the earlier releases, implicit initialization, which was the **only** way to initialize a job prior to that was kept for backwards compatibility.
I think it is time to revisit this on the way to *1.0* and start a deprecation cycle in either direction.

There are two alternatives:

 1. *Any data access* required a prior call to `job.init()`, otherwise an execption is raised.
 2. A call to `project.open_job()` immediately initializes the job.

# Things to consider

 * Explicit initialization is already required using the command line interface.
 * The naming scheme *open_job()* similar to `open()` does not imply that a *file* has been created.
 * Checks like `job in project` wouldn't make any sense any more with *always implicit*  initialization.

**Comment by csadorf** [comment]
@glotzerlab/signac-maintainers I vote to close this issue for good. I think the current approach where both implicit and explicit initialization is possible is fine. What do you think?

**Comment by bdice** [comment]
@csadorf Sounds good to me.

**Comment by csadorf** [comment]
We will keep the current behavior in place.
