### ISSUE TITLE
String conversion needs to be checked

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac#724]
This is a vague TODO: 

https://github.com/glotzerlab/signac/blob/dac2c300a5e541b59ee98427b8b571df1c07aeb9/signac/common/configobj/__init__.py#L1522

Tagging @csadorf  who wrote this TODO 6 years ago in case he has an idea. Regardless, thoughts on this bit of code are welcome.

**Comment by csadorf** [comment]
@atravitz Since you closed it, I assume it is already cleared up, but just to clarify, I do not think that I wrote this TODO. I just authored the commit when we vendored the configobj library.

**Comment by vyasr** [comment]
Yup I pointed out to @atravitz that a number of the issues she was creating corresponded to TODOs inside configobj. Those are all the issues that were opened and then closed.
