### ISSUE TITLE
Remove docstrings for doc_filter parameters

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac#725]
from TODO: https://github.com/glotzerlab/signac/blob/dac2c300a5e541b59ee98427b8b571df1c07aeb9/signac/contrib/project.py#L75

we are removing doc_filter from the API in 2.0.

**Comment by vyasr** [comment]
After numerous discussions, we are instead planning to remove the doc filter entirely in signac 2.0. This is done in #752.
