### ISSUE TITLE
remove support for non-string keys in 2.0

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac#726]
from TODOs:

1. https://github.com/glotzerlab/signac/blob/dac2c300a5e541b59ee98427b8b571df1c07aeb9/signac/synced_collections/validators.py#L59
I think we might want to rename this function also. It's checking for more than a dot in a key if it's also checking type validity.

2. https://github.com/glotzerlab/signac/blob/dac2c300a5e541b59ee98427b8b571df1c07aeb9/signac/synced_collections/backends/collection_json.py#L40

3. https://github.com/glotzerlab/signac/blob/dac2c300a5e541b59ee98427b8b571df1c07aeb9/signac/synced_collections/backends/collection_json.py#L59 

4. https://github.com/glotzerlab/signac/blob/dac2c300a5e541b59ee98427b8b571df1c07aeb9/signac/synced_collections/backends/collection_json.py#L145

**Comment by bdice** [comment]
This is resolved by #719.
