### ISSUE TITLE
Limit type check test to json-required backend

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac#729]
From TODO https://github.com/glotzerlab/signac/blob/dac2c300a5e541b59ee98427b8b571df1c07aeb9/tests/test_synced_collections/synced_collection_test.py#L444

@vyasr  - could you clarify what needs to be done here?

**Comment by vyasr** [comment]
I think my intent with this TODO was to express that different backends would have different sets of valid and invalid keys, so this test doesn't necessarily make sense for all backends. However, the specific keys that are tested here are invalid for all the backends that we currently support, so tests pass as expected.

**Comment by bdice** [comment]
@vyasr Do you recommend one of the following actions, or something else? I'd like to make a path for us to close this issue.
1. Remove the TODO, leave current behavior.
2. Make this test more specific and only run it on the currently implemented backends.

**Comment by vyasr** [comment]
I would recommend option (1). If we run into JSON-specific bugs in the future, we can add additional tests of those invalid keys.

**Comment by bdice** [comment]
Resolved in https://github.com/glotzerlab/signac/commit/7c4c5fb03897ce1504eb99d36afba840148bc932.

**Comment by vyasr** [comment]
@bdice I misread your suggestion, sorry about that. The comment itself is also not valid for the current test, which is checking for keys that we anticipate being invalid for *all* synced collections. I've pushed a commit removing the comment entirely.

Unrelated, when you make changes to permissions that enable pushing to our protected branches, please change those settings back afterwards. The minor annoyance of having to change those settings each time is preferable to having unwary users accidentally pushing commits to them.
