### ISSUE TITLE
Consider removing config APIs

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac#753]
Currently signac allows users to interact with the config via both Python APIs and the CLI. While this model makes sense for most of signac, it is generally unnecessary for configs. In fact, changes like glotzerlab/signac-flow#573 are moving us towards completely decoupling the configuration logic and just sharing the file. We should investigate whether this approach is viable for signac-flow/other plugin compatibility (i.e. if packages built on top of signac could just rely on configobj directly), in which case we could remove config APIs entirely from signac.

**Comment by bdice** [comment]
See: https://github.com/glotzerlab/signac-flow/issues/643

**Comment by vyasr** [comment]
Based on various recent discussions, we can remove config APIs from signac. signac-flow has been updated accordingly.
