### ISSUE TITLE
Remove upper bound on python_requires

### ISSUE THREAD

**Issue by matthewfeickert** [glotzerlab/signac#780]
:wave: At the moment the project has an upper bound on `python_requires`

https://github.com/glotzerlab/signac/blob/aed17f324b3e1f5dfb3328cff6c2ab73ca434929/setup.py#L63

While `signac` is a framework and not a "pure" library, I would still consider it to [not be an application](https://iscinumpy.dev/post/app-vs-library/). I would recommend removing this upper bound on Python 4 for the reasons summarized in Henry's [detailed blog post on the subject](https://iscinumpy.dev/post/bound-version-constraints/) and because the Python Steering Council has made it clear that if there ever is a Python 4 it will not be as radical of a break as Python 2 -> Python 3.

**Comment by bdice** [comment]
Thanks for catching this! I am familiar with those articles and I agree the upper bound should be removed. Upper bounds were used by many libraries in the past and I suspect this was originally influenced by some other library’s choice.
