### ISSUE TITLE
Better API for the modification of configuration files

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#81]
**[Original report](https://bitbucket.org/glotzer/signac/issue/81) by Carl Simon Adorf (Bitbucket: [csadorf](https://bitbucket.org/csadorf), GitHub: [csadorf](https://github.com/csadorf)).**

----------------------------------------

Modifying global, local, and project config files currently requires the use of low-level API as part of the `common.config` namespace. Manipulating the configuration should be simplified with a high-level API.

As an example, it should be possible to change the project's workspace configuration like this:
```
#!python
project.config['workspace_dir'] = '/path/to/new/workspace'
```

**Comment by csadorf** [comment]
We could consider to make `Project.workspace` a property.

**Comment by csadorf** [comment]
I suggest we move this to 1.1, any objections?

**Comment by bdice** [comment]
@vyasr I think this is superseded by #246? If so, please close.

**Comment by vyasr** [comment]
Yes, I don't want to close until that PR is merged but will do so until it is.
