### ISSUE TITLE
My job is always waiting, until all other jobs are done. 

### ISSUE THREAD

**Issue by zhangyemayapro** [glotzerlab/signac#832]
### Description

I'm learning how to use signac. 

When I submit job in the document, my job is always waiting, until all other jobs are done. (The server is not full, I can submit job using sbatch.)

### To reproduce

```
 python project.py submit -o hello_job
```

### Error output

![image](https://user-images.githubusercontent.com/32811826/196024317-d0cd98a5-3ceb-4a44-9343-b07dfc974876.png)

### System configuration

Please complete the following information:

 - Operating System [ubuntu 20.04]:
 - Version of Python [3.10]:
 - Version of signac [1.7.0]:

**Comment by bdice** [comment]
@zhangyemayapro Hi! Can you tell us about:
- The type of cluster (SLURM?)
- The cluster environment/template (is it one of the built in clusters or a custom template/environment definition?)
- Any directives on the operation
- The output of `python project.py submit -o hello_job --pretend`. The pretend flag shows the raw submission script and is useful for debugging.

**Comment by bdice** [comment]
It looks like the job is requesting more resources than are presently available, as shown in the `(Resources)` reason for why it is pending. The information I mentioned above will help us identify why that is happening.

**Comment by zhangyemayapro** [comment]
Thanks for your help~
I find that if I add directives, the slurm can properly handle my job~
@Project.operation.with_directives({"np": 1,"memory": "1g"})

**Comment by bdice** [comment]
Closing as resolved.
