### ISSUE TITLE
Synchronization via Globus

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#84]
**[Original report](https://bitbucket.org/glotzer/signac/issue/84) by Bradley Dice (Bitbucket: [bdice](https://bitbucket.org/bdice), GitHub: [bdice](https://github.com/bdice)).**

----------------------------------------

# Proposal
I propose that `signac sync` could be extended to support Globus transfers with endpoint information saved in the project document. @jglaser and I discussed workflows, and he faces the need to sync frequently with Titan. Being able to use `signac sync` to pull data back and render/plot it immediately on a dashboard would be a very helpful tool.

# Globus Overview
Many users on HPC clusters have access to Globus for file transfers. Access to the filesystem on large clusters such as Titan is tightly controlled for security reasons, but a Globus-based transfer may be a simple and standardized way to support workspace synchronization with many XSEDE and other HPC resources. There are endpoints for Titan, Bridges, Comet, Stampede, and many many more clusters. Our group also has access to Globus endpoints: Flux has support for Globus, and the NFS folder is accessible via the Flux endpoint. Users may also set up their personal machines as Globus endpoints, which Jens did with me in less than five minutes. It was as easy as installing Dropbox.

# How?
There is a well-documented Globus Python SDK.

https://github.com/globus/globus-sdk-python

Using Globus would require a interactive user authentication, at least one time (but possibly each time, depending on our treatment of security and "refresh tokens"). Once authenticated, access tokens are granted and used for API calls to the Globus service.

Refresh tokens can be exchanged for access tokens without re-authentication (the refresh token is an ["infinite lifetime credential"]( https://globus-sdk-python.readthedocs.io/en/stable/tutorial/#advanced-2-refresh-tokens-never-login-again)). It would probably be acceptable to store "refresh tokens" in the user's home directory configuration files but they should not be stored in the project folder.

# Implications for Dashboard
The [Flask OAuth workflow documented here](https://globus-sdk-python.readthedocs.io/en/stable/examples/three_legged_oauth/) would be fully compatible with `signac-dashboard`, enabling users to configure a remote sync source and authenticate without ever leaving the browser. Once tokens were acquired, `signac-dashboard` would return the user's authentication tokens to `signac` and call the sync operation.

With this feature, users could pull fresh workspace data on demand (and perhaps push altered job document keys). Using Globus would also alleviate the difficulties of running a dashboard on a remote HPC system or login node, instead allowing local resources to host the data while remaining in sync with the remote HPC system.

**Comment by vyasr** [comment]
Given the high complexity and the lack of immediate motivation, I'm going to bump this from v2.0.

**Comment by bdice** [comment]
I'm not convinced this needs to be in scope for signac, to be honest. It would be quite complicated and requires skills in API interaction/authentication that aren't necessarily our team's strong suit. If we did anything along these lines, I think that offering a remote backend using SSHFS (potentially via [PyFilesystem2](https://docs.pyfilesystem.org/en/latest/)) would be more suitable than Globus integration. I vote to close.

**Comment by vyasr** [comment]
That's also fine with me. We can reopen if there's future interest.
