### ISSUE TITLE
Make config module internal

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac#874]
The config.py module no longer contains any public APIs. The only publicly visible items are the constants `PROJECT_CONFIG_FN` and `USER_CONFIG_FN`. Should we change this module to `_config`? If so, do we want to keep those two variables public so that users can easily and programmatically see where to expect signac's config files to be stored? To do so I would suggest importing those into `signac/__init__.py` and adding them to `__all__` in that package.

**Comment by bdice** [comment]
I would be fine with making everything private. It is theoretically nice to have `PROJECT_CONFIG_FN` and `USER_CONFIG_FN` as public constants but I don't think anyone uses them in practice.

**Comment by vyasr** [comment]
Fine with me, I don't think anyone's used them in the 6 years signac has existed.
