### ISSUE TITLE
Wrong version being downloaded from conda-forge

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/signac#921]
### Description

When I install a 1.x version of signac, the command line executable downloaded by conda-forge is version 2.0.0 

### To reproduce

Just install signac in a fresh conda environment
```bash
$ mamba create --name signac-one python=3.10 signac=1.8.*
$ mamba activate signac-one
$ signac --version
```

### Error Output

When I run the above code, the output is
```bash
$ signac --version
signac 2.0.0
```
When I run `mamba list`, it says it installed `signac==1.8.0`.

Upon further inspection, the source code that gets installed is in fact signac 1.8.0, but for some reason the executable is version 2.0.0

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: WSL Ubuntu
 - Version of Python [e.g. 3.7]: 3.10
 - Version of signac [e.g. 1.0]: 1.8.0

**Comment by bdice** [comment]
@tommy-waltmann Can you run `which signac`? I suspect you're getting `signac` from another environment. Perhaps a `signac` entrypoint was installed into a location that is higher on your `$PATH` than your conda environment.

**Comment by tommy-waltmann** [comment]
I've tried this on a different OS, and I can't reproduce the behavior. It must be a very odd machine-specific thing.

**Comment by vyasr** [comment]
Do you have signac installed via `pip install --user`, or installed into your base conda environment?

**Comment by tommy-waltmann** [comment]
I have a signac 2.0 installed from conda-forge in my base environment.

**Comment by tommy-waltmann** [comment]
FWIW, installing signac 1.8.0 from source with `pip install .` while inside the `signac-one` environment installed the package properly.

**Comment by vyasr** [comment]
This seems like something odd is happening where the path orderings are mangled. If I had to guess, the Python package in your base environment is somehow higher in your PYTHONPATH than the one in `signac-one` environment, so even though the `signac` executable is being found in the `signac-one` environment, the actual imported signac is coming from somewhere else.

The "executable" installed as a Python entrypoint is really just a Python script. If you open up `/home/tomwalt/mambaforge/envs/signac-one/bin/signac`, you should see it doing something like `from signac.__main__ import main`. Around there can you add an `import signac; print(signac.__file__)` and see where it's actually importing signac from?

**Comment by tommy-waltmann** [comment]
I removed the signac 1.8.0 that I installed from source, reinstalled from conda-forge, and it installed right this time. Everything looks to be installed properly now; I still don't know what was going on before.

**Comment by vyasr** [comment]
I'm going to close this as probably due to some particular issue with the environment. Feel free to reopen if it recurs and you can find a repro.
