### ISSUE TITLE
Search functions are not properly documented

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#95]
**[Original report](https://bitbucket.org/glotzer/signac/issue/95) by Carl Simon Adorf (Bitbucket: [csadorf](https://bitbucket.org/csadorf), GitHub: [csadorf](https://github.com/csadorf)).**

----------------------------------------

There are some issues with the documentation that need to be resolved:

 * The option to search jobs by "job.document" with `find_jobs(doc_filter=f`) is not properly documented.
 * The deprecation of `find_job_documents()` and `find_statepoints()` is indicated through a `DeprecationWarning`, but not explicitly marked in the documentation.

**Comment by vyasr** [comment]
Addressed in #130
